tweepy:
  consumer_key: consumer_key
  consumer_secret:  consumer_secret
  access_token: access_token
  access_token_secret: access_token_secret
discord:
  token: token
api:
  url: url
  user-agent: ua_str